# Конфигурация модуля предсказания новостных всплесков

# Источники RSS новостей (проверенные работающие)
news_sources:
  # Основные деловые СМИ
  - https://www.interfax.ru/rss.asp
  - https://www.kommersant.ru/RSS/news.xml
  - https://lenta.ru/rss
  
  # Альтернативные источники (если основные не работают, раскомментируйте):
  # - https://1prime.ru/export/rss2/index.xml
  # - https://quote.rbc.ru/news/rss/
  # - https://news.yandex.ru/index.rss

# Использовать API вакансий (hh.ru)
use_vacancies: true

# Позитивные ключевые слова (индикаторы роста)
positive_keywords:
  - запуск
  - запущен
  - фьючерс
  - опцион
  - новая секция
  - развитие продукта
  - тестирование платформы
  - лицензия
  - расширение торгов
  - API
  - инновация
  - партнёрство
  - открытие
  - прибыль
  - рост
  - успешно
  - одобрен
  - новый продукт

# Негативные ключевые слова (индикаторы рисков)
negative_keywords:
  - расследование
  - приостановка
  - санкции
  - убытки
  - падение
  - кризис
  - банкротство
  - штраф
  - скандал
  - закрыт
  - отменён
  - приостановлен

# Настройки кэширования (в секундах)
cache_ttl: 3600

# Путь к файлу истории событий
events_log_path: data/events_history.json

# Уровень логирования (DEBUG, INFO, WARNING, ERROR)
log_level: INFO

# Путь к файлу логов
log_file: data/logs/predictor.log

# Ограничение запросов к API (в минуту)
requests_per_minute: 10

# === LLM (локальная нейронка) для глубокого анализа ===
llm:
  enabled: true  # true чтобы включить (сначала установите Ollama!)
  provider: ollama  # ollama, openai, localai (можно добавить свой)
  model: mistral  # mistral, qwen2.5:7b, llama3.1:8b
  base_url: http://localhost:11434
  
  # Когда использовать LLM:
  # - "all" = для всех новостей (медленно, но точно)
  # - "relevant_only" = только для релевантных (рекомендуется)
  # - "uncertain" = только для неоднозначных
  use_for: relevant_only
  
  # Настройки производительности
  timeout: 30  # Максимум секунд на анализ одной новости (первый запрос медленный!)
  confidence_threshold: 0.3  # Порог для "uncertain" режима
  warmup: true  # Прогрев модели при старте

