# Конфигурация правил для системы рекомендаций BUY/HOLD/SELL

# === Дивиденды ===
dy_buy_min: 8.0           # Минимальная дивидендная доходность для покупки (%)
dy_very_high: 15.0        # Порог для очень высоких дивидендов (%)

# === Позиция относительно SMA200 ===
max_discount_vs_sma200: -10.0   # Максимальный дисконт (отрицательное значение, %)
min_premium_vs_sma200: 10.0     # Минимальная премия для продажи (положительное, %)

# === Тренд ===
trend_up_min: 0.5         # Минимальный положительный тренд за 20 дней (%)
trend_down_max: -0.5      # Максимальный отрицательный тренд (%)

# === Границы scoring ===
buy_score_cutoff: 2.0     # Порог score для BUY рекомендации
sell_score_cutoff: -2.0   # Порог score для SELL рекомендации

# === 52W диапазон ===
near_52w_low_threshold: 0.3   # Нижняя треть диапазона (0-0.3)
near_52w_high_threshold: 0.9  # Верхняя граница (0.9-1.0)

# === Модуль предсказания событий ===
event_predictor:
  enabled: true                # Включить/выключить модуль
  weight:
    HIGH_PROBABILITY: 1.5      # Вес для HIGH_PROBABILITY сигнала
    MEDIUM_PROBABILITY: 0.5    # Вес для MEDIUM_PROBABILITY сигнала
    NEGATIVE_SIGNAL: -1.0      # Вес для NEGATIVE_SIGNAL
    LOW: 0.0                   # Вес для LOW (нейтральный)

